
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blgojbidmftvauymedqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsZ29qYmlkbWZ0dmF1eW1lZHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NjMxNzgsImV4cCI6MjA1NjIzOTE3OH0.ucxfEquJggby01acMAP1tCIQSgag-eTt3mS1EmlGNLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
  },
});

// Admin-specific functions
export const isUserAdmin = async (userId: string) => {
  if (!userId) return false;
  
  const { data, error } = await supabase
    .from('profiles')
    .select('is_admin')
    .eq('id', userId)
    .single();
  
  if (error || !data) return false;
  return data.is_admin;
};

export const toggleUserAdminStatus = async (userId: string, status: boolean) => {
  const { error } = await supabase
    .from('profiles')
    .update({ is_admin: status })
    .eq('id', userId);
  
  return { error };
};

export const getAllUsers = async () => {
  return await supabase
    .from('profiles')
    .select('*');
};
